name: beacon_hawkbee
description: Dart implementation of the Beacon protocol for connecting blockchain dApps with wallets
version: 0.1.0
homepage: https://github.com/yourusername/beacon_hawkbee

environment:
  sdk: ^3.0.0

dependencies:
  crypto: ^3.0.3
  uuid: ^3.0.7
  http: ^1.1.0
  web_socket_channel: ^2.4.0

dev_dependencies:
  lints: ^2.1.0
  test: ^1.24.0
